### ISSUE TITLE
kwz.py Can't Decode Byte, Invalid Continuation Byte

### ISSUE THREAD

**Issue by meemo** [Flipnote-Collective/kwz-parser#7] opened 2020-06-13 03:50 UTC
When running kwzAudio.py, it errors out when it reaches line 252 of kwz.py with the error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 0: invalid continuation byte`. This can be remedied by removing `.decode("utf-8")` on line 250 of kwz.py.

Command run was `kwzAudio.py cmz2mklg0c1zqcceks5wrmbp5ien.kwz 0 outputAudio.wav`

**Comment by jaames** [comment] 2020-06-13 20:34
Should be fixed now. I think that issue was caused by the borked filenames that occasionally show up in DSi Gallery notes

btw, I see you tried to fix this in your port - note that removing `decode("utf-8")` is incorrect, you should have replaced all instances of `decode("utf-8")` with `decode()` instead

**Closed by jaames** 2020-06-13 20:34 UTC
